### ISSUE TITLE
Remove languages from data card and display them below the hero

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1034]
We've been finding that displaying languages in the data card is not flexible enough for all our use cases. We're thinking that it'll be more effective to decouple them from the data card and display them always under the hero card. Something like this:

<img width="730" alt="Screenshot 2024-05-22 at 12 24 02" src="https://github.com/international-labour-organization/designsystem/assets/22772102/3f281a0e-ffce-441f-8426-cfab8769bc07">

See test here: https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?node-id=5107-72366&t=7WD1W2uRpdvjugs8-0

And an example of UNICEF handled this: https://www.unicef.org/reports/state-worlds-children-2023

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/f0b6ed2f-9bcb-4a94-a838-f222cd8ab02b)

@beatrizmartinmartins Could you please:
- Refine this design solution, define spacing below, after and within component; font specs; etc.
- Do we need to add this as a new component to the library?
- Add the component to the following templates: Publication, Resource, Event, Project, Multimedia Story
- Remove languages from the data card component

FYI @justintemps so you know this is coming

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins We need to move this to development soon. Could you please give us an update on this?

**Comment by beatrizmartinmartins** [comment]
@inesdgomes I removed the languages from the [Data Card](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=7020-13683&t=BcrzzTsjGNg4AHmh-1) component and included it on the [Hero Card](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=7218-14778&t=BcrzzTsjGNg4AHmh-1) component (it's not visible because it's a component propertie that is currently hidden because we don't need it anywhere, so we can always make it visible whenever we want).

Also, above you can find the different templates updated:

- [Publication](https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?m=auto&node-id=3847-46891&t=XYtfxZcccGfrUf4d-1)
- [Event](https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?m=auto&node-id=3847-46893&t=XYtfxZcccGfrUf4d-1)
- [Project](https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?m=auto&node-id=3847-46895&t=XYtfxZcccGfrUf4d-1)
- [Multimedia Story](https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?m=auto&node-id=3847-46897&t=XYtfxZcccGfrUf4d-1)

The spacing between the text and links is 12px in width and 8 pixels in height between one line and another so it doesn't occupy that much space.

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins Thanks for the work on this. I think though that we shouldn't add the languages to the hero card component. This component is already quite complex and does too many things. Other than that, a few other comments:

- There's a huge space between the languages and the content that comes afterwards. Was this intentional? There are als
- Find it odd that the grey label 'Content also available in' has a different font weight than the languages text. Something seems a bit off.

**Comment by justintemps** [comment]
Hey @inesdgomes and @beatrizmartinmartins, this is a design task for the website but it shouldn't affect the Design System so I think we should close this.

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins Talked to Justin, we're keeping this design task here for now, even if it's not strictly about the design system, but rather about a specific application.

**Comment by beatrizmartinmartins** [comment]
Created the Languages component as we spoke during our weekly meeting [Link to component](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=3831-39188&t=N2JlfCQjknqGMTz2-1) @inesdgomes

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins Could you also update the templates accordingly along with spacing info? I think in the templates the languages are still part of the hero card.

**Comment by beatrizmartinmartins** [comment]
I was wondering, does it make sense to exclude it from the Hero Card? I know we don't have almost any instance where we use the dark hero card at the moment, but if we did (like this example [here](https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?m=auto&node-id=4309-60330&t=0di28TbefqvlDC6M-1)) the languages would be outside the hero card and might look a little bit weird right? So my point here is, should the languages really be outside of the hero card? @inesdgomes

**Comment by beatrizmartinmartins** [comment]
All templates are changed to what we talked during our meeting (make it a component separated from the header) @inesdgomes

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins One final request: could you please add the component to a couple of the Resource templates as well with spacing info? Thanks

**Comment by beatrizmartinmartins** [comment]
Hey @inesdgomes what resources file?

**Comment by beatrizmartinmartins** [comment]
done @inesdgomes

**Comment by inesdgomes** [comment]
Thanks, all good!

**Comment by inesdgomes** [comment]
Closing this ticket because it doesn't require development in the digital design system. Changes will be applied directly in the ILO website.
