### ISSUE TITLE
Twig: Upgrade to Wingsuit 2

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#1046]
This is a stub for upgrading to Wingsuit 2.

Here is a link to the upgrade guide: https://github.com/wingsuit-designsystem/wingsuit/blob/release-2-0/docs/src/app/(docs)/guides/ws2-upgrade/index.mdx

**Comment by justintemps** [comment]
Hey @bashlk and @GGKapanadze, I'm beginning to think that upgrading to Wingsuit 2 is a dead end and that we should instead find a simpler way of rendering our Twig templates in Storybook.

I've been trying to upgrade to the beta version of Wingsuit 2 and it's been really hard going. Also, I feel like it's too much of an abstraction on top of Storybook, which is complicated enough as it is. 

I've prepared a proof of concept that uses a simple Vite plugin [vite-plugin-twig-drupal](https://github.com/larowlan/vite-plugin-twig-drupal) to render the templates. It does a good job of handling the Twig files and can even manage `@includes`.

However, it doesn't handle scripts, which gets a little tricky when components have sub components that have their own JS behaviors. We can either live with that or try to tweak the plugin workflow so that it compiles scripts as well as Twig templates. Anyway, give it a look and see what you think: https://github.com/justintemps/twig-vite-poc

**Comment by bashlk** [comment]
@justintemps Why don't we stop using storybook altogether for the twig components?

Since we are making all the twig components follow the UI patterns spec for the base theme, we could also use the UI patterns environment to play around with the components themselves (See https://www.drupal.org/project/ui_patterns - the base theme docker image already presents this for us) This way, we would be using the same environment during development as a Drupal developer, which would also reduce the chance of us running into the Drupal specific issues that we have had in the past. 

We could still use storybook for the React version of the components so in summary, we would use the base theme docker image to develop the twig components and storybook to develop the React components. We could introduce more variants of the components so that we can preview more states of it and we can also use these for the tests.

The biggest concern I have with vita-plugin-twig-drupal is that there is no community behind it yet, it is mostly one developer working on it. It is the same developer in fact who created [twig-testing-library](https://github.com/larowlan/twig-testing-library) which hasn't been updated in 3 years. So it is likely that this plugin would also not be actively developed in the future.

**Comment by justintemps** [comment]
Hey @bashlk it's a compelling idea, but I'm not sure how you see it working in practice. The dev workflow for building new components in Twig is pretty seamless, I'd hate to lose that. What does my setup look like if I'm developing a new component in Twig for example? Do I have HMR if I'm updating styles for example?

I get your take on [vite-plugin-twig-drupal](https://github.com/larowlan/vite-plugin-twig-drupal), but it's not a super complicated plugin and mostly just implements the npm Twig lib, which has a pretty solid community behind it. I don't think it would be a huge issue to fork and fix if we ever had to.

**Comment by GGKapanadze** [comment]
Ditching the storybook and moving to Drupal seems naive, but let's look for a development workflow. 

1. We introduce Drupal to mono repo
 - It will be harder to maintain
 - we have to introduce a docker setup for `designsystem.` 
 - It'll be more challenging to contribute, if react dev wants to contribute a fix for the `navigation` component, the current setup allows you to switch the mental model to `twig` quickly but in the Drupal case, the overhead will be heavily be increased 
 - Will the `npm` package still be shipped or just a `composer one`? 

2. Create a new repo for twig components development 
 -  How are we going to develop styles consistently? 
 -  We are losing all possible codesharing for `js` for future 

Moving from the storybook is the last resort. I'm making progress with [vite-plugin-twig-drupal](https://github.com/larowlan/vite-plugin-twig-drupal) I want to make it work with `UI` patterns. I'll introduce the concept PR of wingsuit alternative

**Comment by justintemps** [comment]
Hey @GGKapanadze, check out my POC please. The o my thing it’s missing is a utility function to create a default story from the pattern yaml. Otherwise it works more or less like Wingsuit except that it’s way way simpler.
