### ISSUE TITLE
Update all headings levels in designs

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#1061]
The headings levels do not currently follow a logic order in the designs. We should also review whether we should remove headings from inside components (e.g. Links list) - we did this in the website.

**Comment by beatrizmartinmartins** [comment]
@inesdgomes I made all changes to the design templates and now we are using the correct styles within it. Also I realised we do use all text styles within the typography stylesheet.
H1 - Main Headings, Hero Cards, etc
H2 - Promo Card, Stats Card
H3 & H4 - All other main card components
So I don't think we need to remove any text style at the moment. If we remove the H2 and make the Promo Card and Stats Card use the H3, there wouldn't be any hierarchy defined and everything would look the same sizing, so I feel like it's better not to change it. I know we don't use those components that often but when we do, they need to have a bigger hierarchy because they are important.

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Let's review this one together. I think because the section divider is still H3, the headings still do not follow a sequential order. See for example the homepage: we're jumping from H1 to H3.

Also, as for removing headings from within components, I think this can still be done, but let's look at it together.

**Comment by beatrizmartinmartins** [comment]
@inesdgomes Shall we make a fusion between H2 and H3 and only have one heading instead of 2?

**Comment by inesdgomes** [comment]
Agreed that we'll merge H2 and H3 and we'll have only 4 heading levels.

**Comment by beatrizmartinmartins** [comment]
Just made this change. Also applied it to the Promo Card and Stats Card component. Remember that all components that used to have H3, now have H2. @inesdgomes

**Comment by inesdgomes** [comment]
Thanks @beatrizmartinmartins Closing this ticket.
