### ISSUE TITLE
Add "download" icons to icons package, and refactor LinkList to have links display this icon instead of the default arrow

### ISSUE THREAD

**Issue by johnpauldavis** [international-labour-organization/designsystem#253]
The LinkList wasn’t built to handle different icons for different scenarios (because there was only one scenario in the component design when it was built) and will need to be refactored to receive a flag that this link is a download not a destination. It also needs to be worked out if these can be mixed/matched (can one LinkList component contain links of both types?) as well as any of other UX issues (e.g. do the download open in a new tab? Are there restrictions on file type for downloads? Is there error messaging if a download fails?)

**Comment by bashlk** [comment]
@justintemps This needs some design decisions.

**Comment by justintemps** [comment]
@bashlk yea, I'm reassigning this one to @inesdgomes and removing from the V1 milestone for now.

**Comment by justintemps** [comment]
@inesdgomes do we still want to do this? Was reminded of this by #1042

**Comment by inesdgomes** [comment]
@justintemps I'm cancelling this ticket because:
a) Beatriz already added the download icon to the icons package.
b) If we add the option for download to the 'links list' component then it's not really a 'links list' anymore, is it? We'd need to rethink the component, including its name, which would be fine, but don't think it's a priority now.
c) We're already addressing the need for files download in ticket #1042.
