### ISSUE TITLE
Graphic promo card: Add alternative layout

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#371]
Currently the Graphic promo card does not allow for content to be narrow and left-aligned as per design below
<img width="472" alt="Screenshot 2023-06-07 at 14 06 35" src="https://github.com/international-labour-organization/designsystem/assets/22772102/fd42907b-95da-48a0-bffb-5b1e6f59b85a">

See full design here: https://www.figma.com/file/RRxsfLNxjoypKrfJg1EwJf/ILO_Components_Library_LIVING?type=design&node-id=405-3555&t=YD0zPREOdWuo4Jg4-0

The logic should be:
a) if content is horizontally centered on desktop, it should be vertically centered on mobile.
b) if content is left-aligned on desktop, it should be aligned to the bottom on mobile.

**Comment by inesdgomes** [comment]
@PauZoocha I think you flagged this one, but can't remember where. Please see comment from @justintemps - let us know if it's all clear.

**Comment by justintemps** [comment]
So it turns out that the Graphic Promo card (may be others too?) has `alignment` and `size` properties but it's not clear what if anything they do. 

Alignment and size should both be determined by the cards parent, not by the card itself. Refactor to achieve that, also in Card Group which can come with some standard settings for this.
