### ISSUE TITLE
Dropdown: component should support multiple options

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#414]
The [dropdown menu component](https://twig.ui.ilo.org/?path=/docs/components-dropdown--dropdown) opens a panel that allows users to pick only one option. It needs to be changed so it supports multiple selected options.

**Comment by Shashika6** [comment]
@justintemps had a look at this if we use the multiple option in select it is not very UX friendly cause we have to select options from the ctrl key. 

What if we use checkboxes so that the user is given options to select multiple values we can implement it to look like a dropdown. 

@bashlk what do you think ?

**Comment by bashlk** [comment]
Well from what I see, the Dropdown component is using the native HTML select element underneath which shows as a dropdown when a single option needs to be selected. If we ask it to make multiple elements selectable, it will show up like this and it will not be a dropdown. (e.g. https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple)

<img width="157" alt="Screenshot 2024-02-28 at 11 10 33" src="https://github.com/international-labour-organization/designsystem/assets/11556301/58dba758-ff4a-4c10-ba1b-48a0601876cb">

So I think there are two ways in which we can proceed
- Either we create a new component type for the multi select and style the native HTML element to be a design system element (preferred option, least amount of dev work)
- Or we stop using the native HTML select element and implement a fully custom dropdown, where we also control the styling of the component and add checkboxes to the dropdown element. (a lot more work since we have to get the custom dropdown to work across all kinds of screen sizes, handle touch screen behavior and make it accessible.)

Thoughts @inesdgomes?

**Comment by justintemps** [comment]
@inesdgomes, this is sort of a can of worms, can we remove it from v1 release for now and come back to it later?

**Comment by inesdgomes** [comment]
@justintemps Yes, let's put it on hold for now. We addressed this need in the ILO website by changing the dropdown to an accordion with checkboxes and a scroll bar, so this is not urgent now.

**Comment by justintemps** [comment]
Hey @inesdgomes can we close this? It seems like it's not needed.

**Comment by inesdgomes** [comment]
@justintemps We can cancel this ticket.
