### ISSUE TITLE
Define fonts for headings and body copy in each language

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#471]
Adjust design system to define fonts for each of the languages below.

**Overpass for headings / Noto Sans for body copy**
- Dutch
- English
- Italian
- French
- Portuguese
- Spanish
- German

**Noto Sans for both headings and body copy**
- Arabic (requires a specific font package: [Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic))
- Chinese (requires a specific font package: [Noto Sans Simplified Chinese](https://fonts.google.com/noto/specimen/Noto+Sans+SC))
- Japanese (requires a specific font package: [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP))
- Russian
- Turkish
- Ukrainian
- Vietnamese

**All other fonts listed in [ILO content and site languages](https://iloprod.sharepoint.com/:x:/r/teams/INFOTEC-ILOPublicWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B5E173DAD-4A65-46A7-B6CF-06D9B2055F3F%7D&file=ILO%20content%20and%20site%20languages.xlsx&wdOrigin=TEAMS-ELECTRON.p2p.bim&action=default&mobileredirect=true) should display in Noto Sans. If Noto Sans does not support the language, the font should use the system font.**

**Comment by justintemps** [comment]
Hey @inesdgomes 

I realized/remembered that Noto Sans Simplified Chinese is massive. It’s only available as a ttf and each style weighs 10.5MB. Getting regular, bold and italic would require the user to download like 30 MB of font files.

That seems like a bit much to just render a sans-serif font, the performance impact on slow connections would be significant. 

In a previous project when we ran into this problem, I remember we just decided to use Chinese system fonts.

We have the same issue in Japanese, but luckily [it turns out](https://gist.github.com/prantlf/fbd12acc69a022edd589dea48dafe3f8) that Noto Sans CJK JP is a common system font in Japan. We could just check if the user has it and then set some fallbacks.

If that’s acceptable then we could close this ticket just by setting the fonts like so:

**display (headings)**

`Overpass, Noto Sans, Noto Sans CJK JP, TakaoPGothic, PingFang SC, Microsoft YaHei, 微软雅黑, sans-serif`

**copy (body)**

`Noto Sans, Noto Sans CJK JP, TakaoPGothic, PingFang SC, Microsoft YaHei, 微软雅黑, sans-serif`

**Comment by inesdgomes** [comment]
@justintemps As agreed, this works for the 14 site-supported languages. We just need to make sure it also works for the other languages listed here: https://iloprod.sharepoint.com/:x:/r/teams/INFOTEC-ILOPublicWebsite/_layouts/15/Doc.aspx?sourcedoc=%7B5E173DAD-4A65-46A7-B6CF-06D9B2055F3F%7D&file=ILO%20content%20and%20site%20languages.xlsx&wdOrigin=TEAMS-ELECTRON.p2p.bim&action=default&mobileredirect=true
