### ISSUE TITLE
Hero: In mobile, remove top spacing when no image

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#571]
When there's no image in the Hero, we should remove the space for the image in mobile design. Or rather, the space should be less. See designs.

![image](https://github.com/international-labour-organization/designsystem/assets/12401179/44ad1a09-80dd-4d3f-bfe2-fea535087bc8)

**How it should be:**

![Image](https://github.com/international-labour-organization/designsystem/assets/22772102/8a3a66b0-f28e-465f-b047-f84abf83a54f)

**Comment by inesdgomes** [comment]
@justintemps @Shashika6 With this fix, the space was completely removed but there should still be a gap of 48px between breadcrumb and hero on tablet and mobile. Does this need to be fixed in the design system or in the website?

**Website**
<img width="335" alt="Screenshot 2023-12-11 at 10 35 19" src="https://github.com/international-labour-organization/designsystem/assets/22772102/6cb6d9e8-013f-404f-b0f8-4f83fcc74d75">

**Design**
<img width="513" alt="Screenshot 2023-12-11 at 10 34 59" src="https://github.com/international-labour-organization/designsystem/assets/22772102/2675f4e1-3ff6-418e-8fad-2e558b50793a">

**Comment by Shashika6** [comment]
@justintemps The breadcrumb gets hidden when the device is not large is this the expected behaviour ?
