### ISSUE TITLE
Export Styles package from Twig and React packages

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#762]
Right now, we're forcing users to import at least two packages which are both versioned separately if they want to use either component library.

Example, if I'm using the Twig library right now I have to have.

- @ilo-org/twig@0.14.2
- @ilo-org/styles@0.13.1

It's normal for them both to be versioned separately, because not all changes to Twig will affect styles and vice-versa, but we're still making users figure out which versions they need of the two libraries. This is going to be very confusing if you're on an older version and aren't ready to update to the newest one yet.

To solve this, we should export the Styles package directly from the Twig and React packages. They already have it as a dependency, we could just add a build stage where it gets added as an exported package.

That way we could go from this:

```tsx
import { Button } from "@ilo-org/react";
import "@ilo-org/styles/css/button";
```

To something like this:

```tsx
import { Button } from "@ilo-org/react";
import "@ilo-org/react/styles/button";
```
 
You go from having to manage two dependencies as a user to one.

**Comment by bashlk** [comment]
@justintemps Both of the example snippets provided are the same 😄

**Comment by justintemps** [comment]
> @justintemps Both of the example snippets provided are the same 😄

Nope, there's a subtle difference. Look carefully.

**Comment by bashlk** [comment]
Ah my bad, I see it now - it would be better if we don't make the user import the styles in the first place, so that they import only the Button component in this example.

**Comment by justintemps** [comment]
It would but that would make some assumptions about the way the user is
bundling things no?

**Comment by bashlk** [comment]
I don't think so - the styles of the Button are a concern of the design system. 

At least on React, I think we should hide this from the user as much as possible so that they can just import the component and use it without having to manually import the styles as well. I have not used any component library that has made me manually import the styles for each component.

A simple way to achieve this is to add an installation step asking the user to import a stylesheet containing all the styles for the designstem to their index.js / index.ts file (something similar to packages/styles/scss/monorepo.scss). That way with one step, they have all the styles setup for the design system.

The downside of this is that the stylesheet will contain all of the styles, even the styles for components that the user is not using. But given the added convenience, I think the cost will be worth it. Perhaps we can break it down into groups, so that the user can import the stylesheet for a group of components. But even that might be too complicated than required.

Another downside of having the style paths manually exposed is that it restricts our ability to change the folder structure of the styles package. If we do so, we would then need to ask users to change each of the imports manually. But by handling this concern internally and not exposing this to the user, we give ourselves more freedom to adjust the styles package.

**Comment by justintemps** [comment]
In either case @bashlk, the point of this ticket is so that you get the styles from the Twig or the React package, instead of directly from the styles package which you shouldn't even have to download. That way you don't have to worry about which version of the Styles package you're on.

**Comment by bashlk** [comment]
Completed for the twig package in #880.
