### ISSUE TITLE
Breadcrumb gets hidden in small devices

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#782]
@justintemps The breadcrumb gets hidden when the device is not large is this the expected behaviour ?

_Originally posted by @Shashika6 in https://github.com/international-labour-organization/designsystem/issues/571#issuecomment-1868749031_

**Comment by inesdgomes** [comment]
@justintemps Sorry, saw that @Shashika6 mentioned this in another ticket and indeed it shouldn't be working like this. The breadcrumb should still be visible on mobile.

**Comment by GGKapanadze** [comment]
How can I reproduce the hidden breadcrumb? because it works properly in the examples below
@inesdgomes @justintemps 


> Chrome Devtools, iPhone SE
![Image](https://github.com/international-labour-organization/designsystem/assets/36326203/f5bdb787-4b05-4cf5-b7b8-b5fa35a4ea30)

> Physical device, iPhone 15 pro

https://github.com/international-labour-organization/designsystem/assets/36326203/05d1fbad-59c2-41ed-8e78-927dd62a6314

**Comment by justintemps** [comment]
@GGKapanadze Check the hero component, that's where this is happening.

**Comment by Shashika6** [comment]
Picking this up as discussed @GGKapanadze
