### ISSUE TITLE
Japanese font: need to serve NotoSansJP

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#818]
It seems we're serving NotoSans SC or NotoSans CJK fonts in the Japanese interface. This means the interface is showing Chinese characters rather than Japanese characters. We need NotoSansJP to show on Japanese interfaces.

**Comment by bashlk** [comment]
@inesdgomes Can you provide an example of this behavior? or some steps to reproduce this?

**Comment by justintemps** [comment]
@bashlk Check the Japanese text here.

https://iloorgstg.prod.acquia-sites.com/ja/node/886/rohasoneteitaheshi

![Screenshot 2024-02-20 at 13 48 42](https://github.com/international-labour-organization/designsystem/assets/12401179/daf6f7e2-1e3a-40fb-b619-24c8b4736f38)

@inesdgomes we agreed that we don't want to ship Japanese or Chinese fonts in the `fonts` package, because they're huge and most websites just use system fonts anyway. 

Here are the current non-Arabic font-face declarations that we have set in the `themes` package.

```json
{
  "fonts": {
    "display": {
      "value": "Overpass, Noto Sans, Noto Sans CJK JP, TakaoPGothic, PingFang SC, Microsoft YaHei, 微软雅黑, sans-serif"
    },
    "copy": {
      "value": "Noto Sans, Noto Sans CJK JP, TakaoPGothic, PingFang SC, Microsoft YaHei, 微软雅黑, sans-serif"
    }
  }
}
```

The reason some users are seeing Chinese characters instead of Japanese ones is because we have Chinese system fonts specified which are probably installed on the users' machines while the Japanese font `Noto Sans CJK JP` we're asking for isn't. I think the best we can do in this situation is to specify which font Japanese users should see if they don't have `Noto Sans CJK JP` installed.

I did some research it looks like these are our best options:

## Windows

- **Meiryo**: A sans-serif font designed to be clear and readable at small sizes, making it suitable for user interface elements as well as longer texts.
- **Yu Gothic**: Another sans-serif font, similar to Meiryo, but with different design nuances.
- **MS Gothic**: A more traditional, fixed-width font that is often used in documents and programming.
- **MS Mincho:** A serif font that is reminiscent of traditional Japanese print typography, often used in formal documents.

## macOS

- **Hiragino Sans (ヒラギノ角ゴ ProN W3/W6)**: A very common sans-serif font used across macOS and iOS for its readability and modern look.
- **Hiragino Mincho ProN**: A serif font counterpart to Hiragino Sans, offering a more traditional appearance.
- **Osaka**: An older font, less commonly used in recent versions of macOS but still present.

If you can tell us which ones we should use for the copy and which one for display, then we can update the font-face declaration in the `styles` package.

**Comment by inesdgomes** [comment]
HI @justintemps Thanks for investigating this. Let's keep the same font for body copy and display copy - that's what we do for Arabic, Russian, etc. If I understand correctly, I should choose one font for Windows and another one for macOS, correct?
Windows: Yu Gothic
MacOS: Hiragino Sans
