### ISSUE TITLE
Accordion: revise padding around content

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#825]
See comments from Pau here: https://zoocha.atlassian.net/browse/ILO-869

**Comment by justintemps** [comment]
Hey @inesdgomes see my reply in Jira. In short, the reason the padding was added to content of the accordion is because we didn’t want the Accordion to be responsible for the content inside of it. We thought you may want more or less padding inside the accordion given that you can put practically anything inside it that you want. We can change that, but I think first we would need to be sure that the same padding should always apply to anything you put in the Accordion no matter what.
