### ISSUE TITLE
Accessibility: address issues with headings' order in cards

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#865]
@justintemps To be discussed:

- Feature cards: remove all heading tags; links should just be links.
- Graphic promo: change title from H3 to H2.
- Factoids: remove all heading tags, keep just standard paragraph text and one link per card.
- Multilink card: this is a complicated one because the headings should be kept as headings, but the level may change depending on whether the cards' group has a heading or not.

**Comment by justintemps** [comment]
here's what we agree to do:

- Change the `h3` that's hardcoded as the title of the cards to a `p` by default
- Add a `headingLevel` prop that will let the developer use a different heading level than `p` if they need to.

The appearance of the title doesn't change, only the element that's rendered.

## Caveat

We understand that we may have to involve configuring the Promo Card (known as Highlighted Card on the website) so that it takes a H2 instead of the default P

**Comment by justintemps** [comment]
Hey @inesdgomes and @Shashika6 on second thought, I think all of the cards should default to being a `p`. It doesn't make sense to have one default to being an `h2`.
