### ISSUE TITLE
Social media: icons in hero cards are not clear

### ISSUE THREAD

**Issue by inesdgomes** [international-labour-organization/designsystem#927]
CMS users and editors keep getting confused about the function of the icons in the hero card. They think they'll link to social media channels, rather than being share buttons. To be discussed how this could be improved.

<img width="1679" alt="Screenshot 2024-04-09 at 11 30 14" src="https://github.com/international-labour-organization/designsystem/assets/22772102/090891c2-f187-4383-9262-c5868585921e">

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Where can we review this one?

**Comment by beatrizmartinmartins** [comment]
https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=7218%3A14778&t=xiREKhqZcf3yfhXq-1

**Comment by beatrizmartinmartins** [comment]
@inesdgomes In order to create this, I created a [new component](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=3767-23230&t=rZ5CZPTZmjY3L9Tb-1), I think it will be easier to maintain in the long term in case we need to make changes to it.

We have 4 options:
- **Mode**: Light and Dark (for the different bg of the cards)
- **Type**: Open and closed

I also had to include a new icon called Share so we could use it on the new component. You can check that new icon [here](https://www.figma.com/design/szl87D4Zg4MeWXzKWMCCZO/ILO-Icons?node-id=5949-9510&t=KbTko7vRKS00Dlw6-1). cc @justintemps

**Comment by inesdgomes** [comment]
Great @beatrizmartinmartins I quite like this solution. @justintemps I think we can move it to development, but let me know if there's anything that you think doesn't work.

**Comment by justintemps** [comment]
Hey @inesdgomes  and @beatrizmartinmartins I think we'd need to see this in action in the components where it's used. So far as I'm aware it's only used in the hero card. I think the important thing is that it doesn't change the layout when it's open. It shouldn't move things around or change the height or width of the components it's inside of when the user opens it.

**Comment by inesdgomes** [comment]
@justintemps The component is indeed used only in the hero card. Beatriz already added it to the templates and you can see it here: https://www.figma.com/design/TnVsWy6VobbHzZdbHdx3Rb/ILO-Page-Templates?node-id=3763-36970&t=Aee4em4sPrxZxJ4z-0

As for your question on whether the layout changes when it's open, the width should not be affected, but I'm not sure about the height as it seems the rounded rectangle where the social media icons show is slightly taller than the 'Share' text. Is that an issue? Can it be resolved in the code or do you need design changes? cc @beatrizmartinmartins 
<img width="664" alt="Screenshot 2024-08-22 at 12 03 52" src="https://github.com/user-attachments/assets/5c0a3abd-ab32-46be-94b4-500dd84168bf">

**Comment by beatrizmartinmartins** [comment]
@justintemps @inesdgomes when I did this, I was thinking about it, and the conclusion was that the circled container needs to be in absolute position so it doesn't affect the height of the hero cards. Is it possible?

**Comment by Shashika6** [comment]
@inesdgomes can you send me a link to this component in figma for the opened state I cant seem to find it :|

**Comment by justintemps** [comment]
@Shashika6 https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?node-id=3767-23230&node-type=FRAME&t=jTAA2DrY2X75zEDg-0

**Comment by justintemps** [comment]
Before @Shashika6 dives into this, @beatrizmartinmartins and @inesdgomes , could you provide some information about the transitions here?

Questions:

1. Does it only happen on click or on hover?
2. What are the select and focus states?

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins Please see above. Apart from the click/hover, I think all that info is in the design files, but maybe it needs to be clearer. Could you please follow up on this one?

**Comment by beatrizmartinmartins** [comment]
@inesdgomes we don't need selected state, because selected is open or closed version. I did create the hover and focus state though. Check it [here](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=3767-23230&t=x4mnqhRw77iTbdz9-1) The hover and focus states for closed version is the same as the link

**Comment by beatrizmartinmartins** [comment]
@inesdgomes fixed the comments on the Social Media icons and also on the Link component because it wasn't behaving the way intended [https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=3767-23230&t=aVB8uFepBwsqHlC8-1](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=3767-23230&t=aVB8uFepBwsqHlC8-1)

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins I think this looks good, but I'm finding it a bit strange now that we're introducing all these round shapes, which  I think we haven't used anywhere else. Just double checking you tried other options?

**Comment by beatrizmartinmartins** [comment]
I remember we tried to include a simple text above, or just use a simple icon button where you click and the popover opens up. I know what you mean, ILO has all sharp edges or just very subtle border-radius, but it was a way to differentiate between the background and the popover surface. Maybe we can remove the border around the social media icons and just leave the bg as transparent? 

Other options:
- [Link](https://es.pinterest.com/pin/51158145758540161/)
- [Link](https://es.pinterest.com/pin/1030198483485184929/)

@inesdgomes

**Comment by inesdgomes** [comment]
Hi @beatrizmartinmartins We agreed last week that we'd go for something with sharper angles, like this example. https://es.pinterest.com/pin/1030198483485184929/

**Comment by beatrizmartinmartins** [comment]
@inesdgomes done. check the design [here](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?m=auto&node-id=3767-23230&t=JIVvLQYx1iQ47Ijn-1)

**Comment by inesdgomes** [comment]
@beatrizmartinmartins Very nice, thanks! 
@justintemps This is ready for development. [Please see design here](https://www.figma.com/design/RRxsfLNxjoypKrfJg1EwJf/ILO-Components-Library?node-id=1433-3563&node-type=canvas&t=LaDxBJmzMi8Z8mZO-0). The users need to click 'Share' to see the 'Open' state.

**Comment by justintemps** [comment]
Moving this into development with #1284
